spring:
  config:
    import:
      - classpath:security/application-prod.yaml
      - classpath:security/application-docker.yaml
      - classpath:security/application-dev.yaml
  profiles:
    active: docker
    group:
      dev: dev
      docker: docker
      prod: prod

logging:
  level:
    org.hibernate.type.descriptor.sql: trace